source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ArticleView_Example', :exclusive => true do
  pod "ArticleView", :path => "../"
end

target 'ArticleView_Tests', :exclusive => true do
  pod "ArticleView", :path => "../"

  
end
